[package]
name = "know-owl"
version.workspace = true
edition.workspace = true

[lints]
workspace = true

[dependencies]
know-core     = { workspace = true }
know-ontology = { workspace = true }
know-reasoner = { workspace = true }
owl-dl-reasoner = "0.3.0"
horned-owl = "1.4"

[dev-dependencies]
fixtures = { workspace = true }
